<?php

namespace Proxies\__CG__\PersonalPage\ProyectosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publicacion extends \PersonalPage\ProyectosBundle\Entity\Publicacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'id', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'doi', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'paginas', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'titulo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'fecha', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'enlace', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'tipoReporte', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'ciudad', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'congreso', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'issn', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'capitulo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'isbn', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'mostrar', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'journal', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'volumen', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'editorial', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'serie', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'edicion', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'idiomaIngles', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'idtipo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'locale');
        }

        return array('__isInitialized__', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'id', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'doi', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'paginas', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'titulo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'fecha', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'enlace', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'tipoReporte', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'ciudad', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'congreso', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'issn', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'capitulo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'isbn', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'mostrar', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'journal', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'volumen', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'editorial', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'serie', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'edicion', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'idiomaIngles', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'idtipo', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Publicacion' . "\0" . 'locale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publicacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTranslatableLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslatableLocale', array($locale));

        return parent::setTranslatableLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoi($doi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoi', array($doi));

        return parent::setDoi($doi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoi', array());

        return parent::getDoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaginas($paginas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaginas', array($paginas));

        return parent::setPaginas($paginas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaginas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaginas', array());

        return parent::getPaginas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnlace($enlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnlace', array($enlace));

        return parent::setEnlace($enlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnlace', array());

        return parent::getEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoReporte($tipoReporte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoReporte', array($tipoReporte));

        return parent::setTipoReporte($tipoReporte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoReporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoReporte', array());

        return parent::getTipoReporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCongreso($congreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCongreso', array($congreso));

        return parent::setCongreso($congreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCongreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCongreso', array());

        return parent::getCongreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssn($issn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssn', array($issn));

        return parent::setIssn($issn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssn', array());

        return parent::getIssn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapitulo($capitulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapitulo', array($capitulo));

        return parent::setCapitulo($capitulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapitulo', array());

        return parent::getCapitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbn($isbn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbn', array($isbn));

        return parent::setIsbn($isbn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbn', array());

        return parent::getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    public function setMostrar($mostrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMostrar', array($mostrar));

        return parent::setMostrar($mostrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getMostrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMostrar', array());

        return parent::getMostrar();
    }

    /**
     * {@inheritDoc}
     */
    public function setJournal($journal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJournal', array($journal));

        return parent::setJournal($journal);
    }

    /**
     * {@inheritDoc}
     */
    public function getJournal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournal', array());

        return parent::getJournal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolumen($volumen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolumen', array($volumen));

        return parent::setVolumen($volumen);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolumen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolumen', array());

        return parent::getVolumen();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditorial($editorial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditorial', array($editorial));

        return parent::setEditorial($editorial);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditorial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditorial', array());

        return parent::getEditorial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerie($serie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerie', array($serie));

        return parent::setSerie($serie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerie', array());

        return parent::getSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdicion($edicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdicion', array($edicion));

        return parent::setEdicion($edicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdicion', array());

        return parent::getEdicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipo(\PersonalPage\ProyectosBundle\Entity\Tipopublicacion $idtipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipo', array($idtipo));

        return parent::setIdtipo($idtipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipo', array());

        return parent::getIdtipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdiomaIngles($idiomaIngles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdiomaIngles', array($idiomaIngles));

        return parent::setIdiomaIngles($idiomaIngles);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdiomaIngles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdiomaIngles', array());

        return parent::getIdiomaIngles();
    }

}
