<?php

namespace Proxies\__CG__\PersonalPage\ProyectosBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Miembro extends \PersonalPage\ProyectosBundle\Entity\Miembro implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'id', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'nombre', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'apellidop', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'apellidom', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'status', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'linkPagina', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'fotourl', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'alumDecripcion', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'locale');
        }

        return array('__isInitialized__', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'id', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'nombre', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'apellidop', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'apellidom', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'status', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'linkPagina', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'fotourl', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'alumDecripcion', '' . "\0" . 'PersonalPage\\ProyectosBundle\\Entity\\Miembro' . "\0" . 'locale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Miembro $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTranslatableLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslatableLocale', array($locale));

        return parent::setTranslatableLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidop($apellidop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidop', array($apellidop));

        return parent::setApellidop($apellidop);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidop', array());

        return parent::getApellidop();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidom($apellidom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidom', array($apellidom));

        return parent::setApellidom($apellidom);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidom', array());

        return parent::getApellidom();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkPagina($linkPagina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkPagina', array($linkPagina));

        return parent::setLinkPagina($linkPagina);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkPagina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkPagina', array());

        return parent::getLinkPagina();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotourl($fotourl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotourl', array($fotourl));

        return parent::setFotourl($fotourl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotourl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotourl', array());

        return parent::getFotourl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumDescripcion($alumDecripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumDescripcion', array($alumDecripcion));

        return parent::setAlumDescripcion($alumDecripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumDescripcion', array());

        return parent::getAlumDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

}
