parameters:
#    personal_page_proyectos.example.class: PersonalPage\ProyectosBundle\Example

services:
#    personal_page_proyectos.example:
#        class: %personal_page_proyectos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
